apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: essentials
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc # The Kubernetes API server URL
  project: default # Replace with the ArgoCD project name if needed
  source:
    repoURL: git@github.com:Taranpreet26311/argo-testing.git
    targetRevision: HEAD # or specify a commit, tag, or branch
    path: essentials # Path to the directory containing the kustomize
  syncPolicy:
    automated:
      prune: true # Automatically remove resources not in Git repository
