apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-app
  labels:
    app: go
spec:
  replicas: 5
  selector:
    matchLabels:
      app: go
  template:
    metadata:
      labels:
        app: go
    spec:
      containers:
      - name: golang-app
        image: taranpreet26311/argo-v2:latest
        ports:
        - containerPort: 3000
