apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Taranpreet26311/argo-testing.git
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: testns
  syncPolicy:
    retry:
      limit: 2
    automated:
        prune: true 
        selfHeal: true
        allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - Replace=true